SELECT ?constraint ?constraintLabel ?operation ?operationLabel
WHERE {
  ?constraint rdfs:label ?constraintLabel ;
              desmos:involvesOperation ?operation .
  OPTIONAL { ?operation rdfs:label ?operationLabel . }
}